import Head from 'next/head'
import { Stack, Box, Flex } from '@chakra-ui/react'
import SimpleSidebar from 'components/Sidebar'
import Feed from 'components/Timeline/Feed'
import { useSession } from 'next-auth/react'
import { getSession } from 'next-auth/react'

export default function Home({ cars }) {

  
  return (
    <div className=''>

      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



        <Stack direction={'row'} justifyContent={{base:'flex-start',md:'center'}} alignContent={{base:'flex-start',md:'center'}} minH={'100vh'} maxW='2000px'>
          
          <Flex display={{base:'none',md:'flex'}} h='100vh' position={'sticky'} top={0}>
              <Box  h='full' >
              <SimpleSidebar/>

              </Box>

          </Flex>
          
          <Flex  w={{base:'100%',md:'50%'}} h='full'>
          <Box w='full'>
              <Feed posts={cars}/>
            </Box>

          </Flex>


         

        <Flex display={{base:'none',md:'flex'}} w="25%" bgColor={'gray.300'} h="full">
        <Box>
              text
            </Box>
        </Flex>
 

        </Stack>












    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });
  
  let cars = await prisma.Posts.findMany({
    orderBy:{
      created_at:'desc'
    }
  })
  cars = JSON.parse(JSON.stringify(cars))

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: { session,cars },
  };
}

