import Head from 'next/head'
import Image from 'next/image'
import prisma from '../lib/prisma'
import Navbar from 'components/Navbar'
import {Heading, Stack, VStack} from '@chakra-ui/react'
import Cards from 'components/Cards'
import InputField from 'components/InputField'
import { useState } from 'react'

export default function Home({cars}) {



  console.log(cars)
  return (
    <div className='w-full min-h-screen'>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

    <Stack display={'flex'} justifyContent={'center'} alignItems={'center'}>
    <Heading>Cars</Heading> 
    </Stack>


    <VStack w='full'>

    <InputField/>


    <Cards cars={cars}/>
    
    </VStack>








    </div>
  )
}



export async function getServerSideProps() {

  let cars = await prisma.Car.findMany()
  cars = JSON.parse(JSON.stringify(cars))

  return {
    props : { cars }
  }
}