import Head from 'next/head'
import Image from 'next/image'
 import Navbar from 'components/Navbar'
import { Center, Heading, HStack, Spacer, Stack, VStack,Box, Flex, Button } from '@chakra-ui/react'
import Cards from 'components/Cards'
import InputField from 'components/InputField'
import { useState } from 'react'
import SimpleSidebar from 'components/Sidebar'
import Feed from 'components/Timeline/Feed'
import { useSession } from 'next-auth/react'
import { getSession } from 'next-auth/react'
import Link from 'next/link'

export default function Home({ cars }) {
  const { data: session, status } = useSession()
  
  return (
    <div className=''>

      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



        <Stack direction={'row'} justifyContent={{base:'flex-start',md:'center'}} alignContent={{base:'flex-start',md:'center'}} minH={'100vh'} maxW='2000px'>
          <Center>
            <Heading>Youre Not Logged in</Heading>
          </Center>
       <Link href='/signin'>
       <Button>
        Log-In 
      </Button>
       </Link> 


        </Stack>












    </div>
  )
}
